### ISSUE TITLE
faban_client warning

### ISSUE THREAD

**Issue by philipghu** [ParsaLab/cloudsuite#34]
cloudsuite/benchmarks/web-serving/faban_client/files/web20_benchmark/src/workload/driver/Web20Driver.java

When I ran faban_client, I got the warning every time a new user logged in: 
  ....
    [java] Logging in: ZIFdBLBGXk
     [java] Mar 15, 2016 11:52:08 PM com.sun.faban.driver.transport.sunhttp.ThreadCookieHandler$CookieStore select
     [java] WARNING: Request http://web_server:8080/ does not contain a hostname or has an invalid hostname.
     [java] Mar 15, 2016 11:52:08 PM com.sun.faban.driver.transport.sunhttp.ThreadCookieHandler$CookieStore select
     [java] WARNING: Request http://web_server:8080/ does not contain a hostname or has an invalid hostname.
     [java] Mar 15, 2016 11:52:09 PM com.sun.faban.driver.transport.sunhttp.ThreadCookieHandler$CookieStore select
     [java] WARNING: Request http://web_server:8080/ does not contain a hostname or has an invalid hostname.
     [java] hostUrl + LOGIN_URL: http://172.18.0.02:8080/action/login // this line was added by myself to see the login
     [java] PRINT: Successfully logged in
     ....

The requests seemed to have reached the web server Ok which means I had the correct web server ip address for the faban_client.

**Comment by nooshin-mirzadeh** [comment]
There is no problem with the warning. It works correctly, please ignore it.
