### ISSUE TITLE
Web serving benchmark: No run.sh file!

### ISSUE THREAD

**Issue by MrAta** [ParsaLab/cloudsuite#40]
Hi
In web serving benchmark all steps run well, but the last step which wants to run ./run.sh is the problem!
in fact there is no file named run.sh in client container. 
The mentioned file run.sh is in which container? server or  client?

thank.

**Comment by aledaglis** [comment]
Hi,

The script is not in any of the containers; it's supposed to launch them. You can get it separately from here: https://github.com/ParsaLab/cloudsuite/blob/master/benchmarks/web-serving/run.sh

**Comment by MrAta** [comment]
thank for your response.
but the problem is now where should i run this file? in host or in container?
the out put of running file in client container  is:
`./run.sh: line 1: docker: command not found
./run.sh: line 1: $'\357\273\277docker': command not found
./run.sh: line 2: $'\r': command not found
./run.sh: line 3: docker: command not found
./run.sh: line 4: docker: command not found
./run.sh: line 5: docker: command not found
./run.sh: line 6: docker: command not found
./run.sh: line 7: docker: command not found
./run.sh: line 8: docker: command not found
./run.sh: line 9: docker: command not found
./run.sh: line 10: docker: command not found
./run.sh: line 11: docker: command not found
./run.sh: line 12: docker: command not found`

and the output of running file in host is:
`: No such file or directoryhmark/deploy/run.xml
: No such file or directoryhmark/deploy/run.xml
: No such file or directoryhmark/deploy/run.xml
: No such file or directoryhmark/deploy/run.xml
: No such file or directoryhmark/deploy/run.xml
: No such file or directoryhmark/deploy/run.xml
Buildfile: /web20_benchmark/build.xml
BUILD FAILED
" does not exist in the project "Faban Benchmark".
Total time: 0 seconds
cat: /faban/output/*/summary.xml: No such file or directory`

**Comment by nooshin-mirzadeh** [comment]
Hi,

You need to run it on the host.

Regards,
Nooshin

**Comment by MrAta** [comment]
@aledaglis I've updated the output of running in host. why i get this output?
it says cant find docker! but the desired container exists! here:
`6f412d8e2a58        cloudsuite/web-serving:faban_client   "/etc/bootstrap.sh -b"   16 minutes ago      Up 16 minutes  faban_client`

**Comment by nooshin-mirzadeh** [comment]
Are you sure you can run any other "docker" command in your terminal? Can you please try to run the run.sh with sudo?

**Comment by MrAta** [comment]
Yeas, we always run docker command and scripts with sudo because  docker does not run without sudo. and the mentioned error has been raised with sudo.
other docker command run very well, for example running this command will execute docker container and we go to container terminal:

`sudo docker exec -it faban_client bash`

**Comment by MrAta** [comment]
Yeas, we always run docker command and scripts with sudo because  docker does not run without sudo. and the mentioned error has been raised with sudo.
other docker command run very well, for example running this command will execute docker container and we go to container terminal:

`sudo docker exec -it faban_client bash`

**Comment by MrAta** [comment]
Yeas, we always run docker command and scripts with sudo because  docker does not run without sudo. and the mentioned error has been raised with sudo.
other docker command run very well, for example running this command will execute docker container and we go to container terminal:

`sudo docker exec -it faban_client bash`

**Comment by shane-Git** [comment]
I think the problem is you forgot to name the faban container.
`CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                      PORTS               NAMES
8acc160ea176        cloudsuite/web-serving:faban_client       "/etc/bootstrap.sh -b"   16 hours ago        Exited (137) 15 hours ago                       faban_client`
Could you please paste your docker ps?
