### ISSUE TITLE
Data Analytics: mahout error

### ISSUE THREAD

**Issue by MrAta** [ParsaLab/cloudsuite#41]
HI,
In Data analytic benchmark, in final step which is running  `./run.sh` every thing goes forward well,
but some mahout commands in the end of file do not run correctly and encounter some error:

`Running on hadoop, using /opt/new_analytic/hadoop-2.7.1/bin/hadoop and HADOOP_CONF_DIR= MAHOUT-JOB: /opt/new_analytic/apache-mahout-distribrtuon-0.11.0/examples/target/mahout-examples-0.11.0-job.jar 
ERROR MahoutDriver: : Try new vector backed naivebays classifier see examples/bin/classify-20newsgroups.sh`
and according to [this link](http://stackoverflow.com/questions/14492937/what-is-the-alternative-of-prepare20newsgroups-in-the-new-version-of-mahout) and [this link](https://issues.apache.org/jira/browse/MAHOUT-1006) it seems the mahout in image file has deprecated files.

**Comment by MrAta** [comment]
The error comes from last two lines of `run.sh` which are:
`mahout trainclassifier -i traininginput -o wikipediamodel -mf 4 -ms 4`
`mahout testclassifier -m wikipediamodel -d wikipediainput --method mapreduce`

these lines of code are using `trainclassifier` and `testclassifier` mahout classes which absolutely have been deprecated since a ling time. [[source](https://github.com/apache/mahout/search?utf8=%E2%9C%93&q=trainclassifier)]

what can we should do?
thank

**Comment by nooshin-mirzadeh** [comment]
Dear Ata, 

Thanks for pointing out this error.
Yes, there is a problem with it, and I need to apply some modification. I will update the image asap, and let you know about it.

Regards,
Nooshin

**Comment by MrAta** [comment]
Is There any update(after 17 days!) ?

**Comment by nooshin-mirzadeh** [comment]
Sorry for the delay. The new image will be available at the end of the week.

**Comment by johnfes** [comment]
have the same problem.

**Comment by nooshin-mirzadeh** [comment]
Hi all,
The new data analytics docker image is available now. Please pull the new images. 

Sorry for the delay.

Regards,
Nooshin
