### ISSUE TITLE
No README

### ISSUE THREAD

**Issue by boompig** [ParsaLab/cloudsuite#54]
There's no README. Would be useful to know:
- license
- how code is organized
- any prerequisite setup required

**Comment by neo-apz** [comment]
Thanks for pointing out these.
Regarding license, the information is available on our [webpage](http://cloudsuite.ch/licenses/). We'll soon add it to the repo as well.
Regarding other points, they are also addressed on our webpage, but we'll soon add a general README file to the root directory explaining these.
