### ISSUE TITLE
Absolute URLs in web server

### ISSUE THREAD

**Issue by boompig** [ParsaLab/cloudsuite#57]
Since the web server is running inside docker, the absolute URLs will not resolve if you want to access the services from outside the container. For example, when you go to the web server main page I see this:
![screen shot 2016-06-08 at 3 21 40 pm](https://cloud.githubusercontent.com/assets/2791268/15913029/b339b32c-2d8c-11e6-82c3-a596edf9e6b9.png)

And I see the following errors in the console:

![screen shot 2016-06-08 at 3 22 15 pm](https://cloud.githubusercontent.com/assets/2791268/15913055/c76756d8-2d8c-11e6-8808-f57980f10aa8.png)

Notice how both hostname and port number are hard-coded, though I am accessing the server on both a different port and a different hostname. Maybe these URLs are generated by the backend, so it thinks the hostname and port are x and y, whereas they are actually remapped outside the container. To fix, these need to be relative paths instead.

**Comment by ivonindza** [comment]
Unfortunately they are hard-coded at the moment. It will be fixed in a later release, but for the moment you can simply add an entry to your hosts file.

**Comment by boompig** [comment]
To anyone who finds this via a Google search in the future:

To access the container from the host, modify the web server command to
```sh
docker run -dt -p 8080:8080 --net=my_net --name=web_server cloudsuite/web-serving:web_server /etc/bootstrap.sh
```

Then you set up an SSH tunnel from the remote machine (the one trying to access the web server) to the host running docker:

```
ssh ubuntu@<docker host IP> -NL 8080:localhost:8080
```

Then you set up this rule in `/etc/hosts` on the remote machine (the one trying to access the web server):
```
127.0.0.1       web_server
```

Then navigate to http://localhost:8080 and you should see something like this:
![screen shot 2016-06-08 at 4 50 20 pm](https://cloud.githubusercontent.com/assets/2791268/15914846/153f41c0-2d99-11e6-9d9b-e015e94e3ce4.png)

**Comment by neo-apz** [comment]
The web-serving benchmark has been redesigned and updated (#70).
